### ISSUE TITLE
Doesn't work max/min changing

### ISSUE THREAD

**Issue by GovardFilipsovich** [ros-visualization/rqt_robot_steering#17]
Whe I use max/min edits, nothing changing in message
After compiling plugin from source, I found error: when I change max, I get in terminal:

self._widget.x_linear_slider.setMaximum(value * MecanumPlugin.slider_factor)
TypeError: setMaximum(self, int): argument 1 has unexpected type 'float'

Probably, its root of problem

**Comment by GovardFilipsovich** [comment]
I'm sorry, if I'm wrong

**Comment by lucasw** [comment]
This is solved by https://github.com/ros-visualization/rqt_robot_steering/pull/13 - you could build https://github.com/lucasw/rqt_robot_steering/tree/python310 from source to use it until it is merged here

**Comment by GovardFilipsovich** [comment]
Thank you
